# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: '#StackCode - A daily screenshot from the Stack Overflow codebase'
description: 'A daily screenshot from the Stack Overflow codebase from Nick Craver.'
baseurl: "/stackcode" # the subpath of your site, e.g. /blog
url: "http://romansp.github.com/stackcode" # the base hostname & protocol for your site
twitter_username: rpvlv
github_username:  romansp

# Build settings
markdown: kramdown
